### ISSUE TITLE
No sync and no shares possible. Error /appinfo/app.php is deprecated

### ISSUE THREAD

**Issue by pzdaniel** [scubajeff/lespas#74]
Hi guys,

first of all, thanks for your great work which I assume is working for many people. Unfortunately I can't get your app to work. Tried many things but I'm not able to share and/or  sync my photos.

I get these messages on nextcloud 23 (just updated from 21 where I got the same messages):

```
00:00","remoteAddr":"172.18.0.1","user":"--","app":"maps","method":"GET","url":"/ocs/v2.php/apps/files_sharing/api/v1/shares?path=lespas&subfiles=true&reshares=false&format=json","message":"/appinfo/app.php is deprecated, use \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class instead.","userAgent":"LesPas_v2.5.11","version":"23.0.4.1"}
{"reqId":"KeTzu2n9cl53fg5TzY1l","level":0,"time":"2022-06-06T11:51:54+00:00","remoteAddr":"172.18.0.1","user":"--","app":"maps","method":"GET","url":"/ocs/v2.php/apps/files_sharing/api/v1/shares?shared_with_me=true&format=json","message":"/appinfo/app.php is deprecated, use \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class instead.","userAgent":"LesPas_v2.5.11","version":"23.0.4.1"}
{"reqId":"9vsj5JgTGT7FxNg0WVAE","level":0,"time":"2022-06-06T11:51:55+00:00","remoteAddr":"172.18.0.1","user":"--","app":"maps","method":"PROPFIND","url":"/remote.php/dav/files/user1","message":"/appinfo/app.php is deprecated, use \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class instead.","userAgent":"LesPas_v2.5.11","version":"23.0.4.1"}
{"reqId":"dILczA1nGA46NmFKSWzo","level":0,"time":"2022-06-06T11:51:55+00:00","remoteAddr":"172.18.0.1","user":"--","app":"maps","method":"GET","url":"/remote.php/dav/files/user1/somepath1/578941.json","message":"/appinfo/app.php is deprecated, use \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class instead.","userAgent":"LesPas_v2.5.11","version":"23.0.4.1"}
{"reqId":"l4qxNJDlPRnIASshcxDE","level":0,"time":"2022-06-06T11:51:56+00:00","remoteAddr":"172.18.0.1","user":"--","app":"maps","method":"GET","url":"/remote.php/dav/files/user1/somepath2/1325935.json","message":"/appinfo/app.php is deprecated, use \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class instead.","userAgent":"LesPas_v2.5.11","version":"23.0.4.1"}
```

Can you maybe give me a hint or advice what I can try next to solve this problem?
Thanks :-)

**Comment by scubajeff** [comment]
Done a quick search on the message, seems like it's an issue introduced in NC 20.x, but this warning message is no harm according to those search hits. So if you can't sync or share,  there must be something else. In Setting screen, under Sync category, what do you see in the sync status summary?

**Comment by pzdaniel** [comment]
Thanks for your reply,
I see (translated):
1. Sync camera roll "on": New photos and videos are synced automatically to "DCMI/oneplus_2023". 14 elements are waiting
2. Intervall syncing: "grey/on": 2 elements are waiting
3. Sync only with wifi "on"

**Comment by scubajeff** [comment]
Would this help? https://help.nextcloud.com/t/not-able-to-login-and-nextcloud-logs-shows-appinfo-app-php-is-deprecated-error-message/112762/4

**Comment by pzdaniel** [comment]
session.save_path was configured correctly (path in docker: " /usr/local/etc/php/conf.d/redis-session.ini"). Disabled redis etc. but still doesn't work. Other apps are working fine though :-(

**Comment by scubajeff** [comment]
Need your setup detail.
Are you using public domain name, or self register domain name, or even ip address to access your NC server?
Are you using https? If yes, are you using self-signed certificate?
Do you know how to collect Android log?
Can your server be accessed from Internet? If yes, I'll be able to do some debugging from my side if you mail me the address.

**Comment by pzdaniel** [comment]
I'm using public domain name (you received an EMail with my nextcloud domain).
Using https with letsencrypt
I haven't used Android SDK/Logging for a while, but I think I can manage it.

**Comment by scubajeff** [comment]
Let me do some test on my side first.

**Comment by scubajeff** [comment]
Do you see lespas/ and DCIM/ folders created in your account's home folder?

**Comment by pzdaniel** [comment]
No lespas didn't create those folders, I now created them manually (with the nextcloud app on the same device) but still not working.

**Comment by scubajeff** [comment]
so every webdav call to server had been denied. the login process finished because it's not webdav but rather an ordinary http access with special OCS api header. do you have other 3rd party app which use NC as the backend? Like Joplin or Davx5?

**Comment by pzdaniel** [comment]
I have DAVx5 and installed also Joplin which are both working fine. Tried to create some folders with Total Commander (WebDAV Plugin) which is also working.

**Comment by scubajeff** [comment]
Then I have no idea what is happening without the log. Two way to work this out:

1. Either you help collecting logcat output during app startup. Les Pas will sync once when it start and the first thing it does is to make sure there is a lespas/ folder created on server, the logcat will show what is happening.
2. Or you can create an testing account on your server for me, and I will do the debugging on my side.

**Comment by pzdaniel** [comment]
Hi scubajeff,

here is the logcat output. Additionally I will create you an user on my instance. Thank you very much for your help.

`
2022-06-20 07:28:12.126 12161-12161/? I/eos.apps.lespa: Late-enabling -Xcheck:jni
2022-06-20 07:28:12.144 12161-12161/? E/eos.apps.lespa: Unknown bits set in runtime_flags: 0x40000000
2022-06-20 07:28:12.150 12161-12161/? D/ProcessState: Binder ioctl to enable oneway spam detection failed: Invalid argument
2022-06-20 07:28:12.153 12161-12161/? I/OneTrace: Mark active for pid=12161? true
2022-06-20 07:28:12.153 12161-12161/? D/cutils-dev: otrace_set_tracing_enabled? true
2022-06-20 07:28:12.191 12161-12176/? D/cutils-dev: properties changed in otrace_seq_number_changed!
2022-06-20 07:28:12.206 12161-12161/site.leos.apps.lespas D/CompatibilityChangeReporter: Compat change id reported: 171979766; UID 10774; state: ENABLED
2022-06-20 07:28:12.207 12161-12161/site.leos.apps.lespas I/oplus.android.OplusFrameworkFactoryImpl: get feature:IOplusAutoResolutionFeature
2022-06-20 07:28:12.207 12161-12161/site.leos.apps.lespas I/oplus.android.OplusFrameworkFactoryImpl: getOplusAutoResolutionFeature
2022-06-20 07:28:12.207 12161-12161/site.leos.apps.lespas D/CompactWindowAppManager: initCompactApplicationInfo 
2022-06-20 07:28:12.229 12161-12161/site.leos.apps.lespas I/OplusFeatureCache: Milliseconds spent on init(): 14
2022-06-20 07:28:12.231 12161-12161/site.leos.apps.lespas D/LoadedApk: mApplicationInfo overrideDisplayId:null
2022-06-20 07:28:12.404 12161-12161/site.leos.apps.lespas V/GraphicsEnvironment: ANGLE Developer option for 'site.leos.apps.lespas' set to: 'default'
2022-06-20 07:28:12.404 12161-12161/site.leos.apps.lespas V/GraphicsEnvironment: Updatable production driver is not supported on the device.
2022-06-20 07:28:12.407 12161-12161/site.leos.apps.lespas D/NetworkSecurityConfig: Using Network Security Config from resource network_security_config debugBuild: true
2022-06-20 07:28:12.408 12161-12161/site.leos.apps.lespas D/NetworkSecurityConfig: Using Network Security Config from resource network_security_config debugBuild: true
2022-06-20 07:28:12.430 12161-12161/site.leos.apps.lespas D/WM-WrkMgrInitializer: Initializing WorkManager with default configuration.
2022-06-20 07:28:12.489 12161-12188/site.leos.apps.lespas D/CompatibilityChangeReporter: Compat change id reported: 160794467; UID 10774; state: ENABLED
2022-06-20 07:28:12.513 12161-12161/site.leos.apps.lespas I/oplus.android.OplusFrameworkFactoryImpl: Unknow feature:IOplusTextViewRTLUtilForUG
2022-06-20 07:28:12.537 12161-12161/site.leos.apps.lespas D/ScrollOptimizationHelper: can't find the config file for optimizaiton
2022-06-20 07:28:12.537 12161-12161/site.leos.apps.lespas D/ScrollOptimizationHelper: will not debug for debug is false
2022-06-20 07:28:12.537 12161-12161/site.leos.apps.lespas I/oplus.android.OplusFrameworkFactoryImpl: get feature:IOplusDynamicVsyncFeature
2022-06-20 07:28:12.537 12161-12161/site.leos.apps.lespas I/oplus.android.OplusFrameworkFactoryImpl: get feature:IOplusDynamicVsyncFeature
2022-06-20 07:28:12.537 12161-12161/site.leos.apps.lespas I/oplus.android.OplusFrameworkFactoryImpl: get feature:IOplusDynamicVsyncFeature
2022-06-20 07:28:12.553 12161-12161/site.leos.apps.lespas W/eos.apps.lespa: Accessing hidden method Landroid/view/View;->computeFitSystemWindows(Landroid/graphics/Rect;Landroid/graphics/Rect;)Z (unsupported, reflection, allowed)
2022-06-20 07:28:12.554 12161-12161/site.leos.apps.lespas W/eos.apps.lespa: Accessing hidden method Landroid/view/ViewGroup;->makeOptionalFitsSystemWindows()V (unsupported, reflection, allowed)
2022-06-20 07:28:12.555 12161-12161/site.leos.apps.lespas E/OplusCustomizeRestrictionManager: sInstance is null, start a new sInstance
2022-06-20 07:28:12.615 12161-12161/site.leos.apps.lespas I/Quality: ActivityThread: activityStart delay 159 site.leos.apps.lespas 12161
2022-06-20 07:28:12.624 12161-12161/site.leos.apps.lespas V/MediaStore: Examining volume emulated;0 with name external_primary and state mounted
2022-06-20 07:28:12.666 12161-12161/site.leos.apps.lespas I/oplus.android.OplusFrameworkFactoryImpl: get feature:IOplusDynamicVsyncFeature
2022-06-20 07:28:12.666 12161-12161/site.leos.apps.lespas I/oplus.android.OplusFrameworkFactoryImpl: get feature:IOplusDynamicVsyncFeature
2022-06-20 07:28:12.666 12161-12161/site.leos.apps.lespas I/oplus.android.OplusFrameworkFactoryImpl: get feature:IOplusDynamicVsyncFeature
2022-06-20 07:28:12.775 12161-12161/site.leos.apps.lespas V/MediaStore: Examining volume emulated;0 with name external_primary and state mounted
2022-06-20 07:28:12.777 12161-12161/site.leos.apps.lespas D/OplusInputMethodUtil: init DEBUG to false, update DEBUG_IME to false
2022-06-20 07:28:12.777 12161-12161/site.leos.apps.lespas D/OplusInputMethodUtil: init DEBUG to false, update DEBUG_IME to false
2022-06-20 07:28:12.784 12161-12161/site.leos.apps.lespas D/OplusSlideAnimOptHelper: site.leos.apps.lespas scrollEffectOpt enable = false
2022-06-20 07:28:12.788 12161-12161/site.leos.apps.lespas D/WindowManager: Add to mViews: DecorView@4b46512[MainActivity],pkg= site.leos.apps.lespas
2022-06-20 07:28:12.790 12161-12189/site.leos.apps.lespas D/ExtensionsLoader: createInstance(64bit) : createExtendedFactory
2022-06-20 07:28:12.792 12161-12189/site.leos.apps.lespas D/ExtensionsLoader: Opened libhwuiextimpl.so
2022-06-20 07:28:12.792 12161-12161/site.leos.apps.lespas D/ExtensionsLoader: createInstance(64bit) : createExtendedFactory
2022-06-20 07:28:12.792 12161-12161/site.leos.apps.lespas D/ExtensionsLoader: Opened libSchedAssistExtImpl.so
2022-06-20 07:28:12.792 12161-12161/site.leos.apps.lespas E/eos.apps.lespa: ofbOpen failed with error=No such file or directory
2022-06-20 07:28:12.792 12161-12161/site.leos.apps.lespas E/eos.apps.lespa: sysOpen failed with error=No such file or directory
2022-06-20 07:28:12.807 12161-12161/site.leos.apps.lespas I/Quality: Skipped: false 1 cost 8.810148 refreshRate 0 processName site.leos.apps.lespas
2022-06-20 07:28:12.808 12161-12161/site.leos.apps.lespas D/ExtensionsLoader: createInstance(64bit) : createExtendedFactory
2022-06-20 07:28:12.808 12161-12161/site.leos.apps.lespas D/ExtensionsLoader: Opened libSchedAssistExtImpl.so
2022-06-20 07:28:12.827 12161-12161/site.leos.apps.lespas D/ExtensionsLoader: createInstance(64bit) : createExtendedFactory
2022-06-20 07:28:12.828 12161-12161/site.leos.apps.lespas D/ExtensionsLoader: Opened libSchedAssistExtImpl.so
2022-06-20 07:28:12.829 12161-12161/site.leos.apps.lespas V/OplusZoomWindowDecorViewHelper: setLastReportedMergedConfiguration mZoomDisplayHeight: 2376 getDecorView.78931218
2022-06-20 07:28:12.830 12161-12189/site.leos.apps.lespas I/AdrenoGLES-0: QUALCOMM build                   : 629d727fc2, I97e7a4565c
    Build Date                       : 03/08/22
    OpenGL ES Shader Compiler Version: EV031.32.02.06
    Local Branch                     : 
    Remote Branch                    : 
    Remote Branch                    : 
    Reconstruct Branch               : 
2022-06-20 07:28:12.830 12161-12189/site.leos.apps.lespas I/AdrenoGLES-0: Build Config                     : S P 10.0.7 AArch64
2022-06-20 07:28:12.830 12161-12189/site.leos.apps.lespas I/AdrenoGLES-0: Driver Path                      : /vendor/lib64/egl/libGLESv2_adreno.so
2022-06-20 07:28:12.836 12161-12189/site.leos.apps.lespas I/AdrenoGLES-0: PFP: 0x016dd091, ME: 0x00000000
2022-06-20 07:28:12.860 12161-12189/site.leos.apps.lespas D/hw-ProcessState: Binder ioctl to enable oneway spam detection failed: Invalid argument
2022-06-20 07:28:12.941 12161-12181/site.leos.apps.lespas D/SurfaceComposerClient: VRR [FRTC] client handle [bufferId:18446744073709551615 framenumber:0] [ffffffff, ffffffff]
2022-06-20 07:28:12.965 12161-12161/site.leos.apps.lespas I/Quality: Skipped: false 17 cost 149.83382 refreshRate 0 processName site.leos.apps.lespas
2022-06-20 07:28:13.010 12161-12161/site.leos.apps.lespas I/Quality: Skipped: false 3 cost 29.050991 refreshRate 0 processName site.leos.apps.lespas
`

**Comment by scubajeff** [comment]
Are you using a authentication backend like LDAP?

**Comment by scubajeff** [comment]
@pzdaniel I just created an album successfully with the testing account your setup for me. So I guess the "Two-Factor TOTP Provider" might be the issue here. Could you please have a look on your server, to see if your account's home folder name match with your account's login name? If they don't, this would be the same issue as #71, and you might want to try the debug build I post over there.

I know you're kind of busy right now, so take your time and really appreciate the help you gave to this app.

**Comment by pzdaniel** [comment]
@scubajeff Thanks for your reply.
I tried the debug apk in your post at issue #71 but it doesn't behave any other than the non debug app. Username seems to be correct.
Additionally I created a new account for myself like I did for you. Still doesn't work.
At last I tried to use your user on my instance, but even this doesn't work, which seems pretty crazy for me, because your device worked fine.
So as of now I think it has something to do with my smartphone/app combination (Oneplus 8 Pro). I will now try other devices to narrow down the problem.

**Comment by pzdaniel** [comment]
Ok, tried it with an Oneplus 6, works like a charm. Same user a.s.o.
So the problem seems to be the Oneplus 8t with Android Version 12

**Comment by scubajeff** [comment]
Glad to know it works. 4GB left doesn't seem to be a problem. Anyway, you can delete the test account now.

**Comment by pzdaniel** [comment]
So finally I got les pas working on my oneplus 8 pro. It seems to be indeed the new (?) "low storage no sync" feature of android 12. As soon as I got enough free space (10% or 12GB !!!) that DAVx5 won't show the low storage warning any more, les pas started to sync.
The bad thing about les pas is, that it is not showing an error or anything else to warn the user, that no sync activities are possible because of low storage (which is below 10% of the total storage!!!). Maybe you could look into that issue and notify the user in feature releases?
Thank you very much for your time and effort to narrow down the problem :-)

**Comment by scubajeff** [comment]
I see. Both Lespas and DAVx5 use android sync adapter to sync. You can see this in your system setting -- accounts menu. This explains that they both have the same behavior.
